'use strict';
const $=id=>document.getElementById(id);
const pages=['incident','patient','primary','secondary','observations','consent','trauma','interventions','drugs','als','outcome','signoff'];
const labels={incident:'Incident',patient:'Patient',primary:'Primary',secondary:'Secondary',observations:'Observ.',consent:'COI',trauma:'Trauma',interventions:'Intervent.',drugs:'Drugs',als:'ALS',outcome:'Outcome',signoff:'Sign off'};
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));$('pageTitle').textContent=labels[id];localStorage.setItem('prf_page',id);growAll();}
pages.forEach(id=>{const b=document.createElement('button');b.className='nav-button';b.dataset.page=id;b.textContent=labels[id];$('nav').appendChild(b);});
document.addEventListener('click',e=>{if(e.target.dataset.page)showPage(e.target.dataset.page);if(e.target.dataset.close)$(e.target.dataset.close).classList.remove('open');});
function grow(el){if(el?.tagName==='TEXTAREA'){el.style.height='auto';el.style.height=Math.max(34,el.scrollHeight)+'px';}}
function growAll(root=document){root.querySelectorAll('textarea').forEach(grow);}
new MutationObserver(records=>records.forEach(r=>r.addedNodes.forEach(n=>{if(n.nodeType===1)growAll(n);}))).observe(document.body,{childList:true,subtree:true});
document.addEventListener('input',e=>{grow(e.target);updatePrimary();updateAlert();clearTimeout(window.saveTimer);window.saveTimer=setTimeout(saveDraft,250);});
window.addEventListener('beforeprint',growAll);
const schemas={incident:['Surge level','CAD Daily ID','Type','CAD ID','Call type','Building number / name','CAD call sign','Road name','Scene contact number','District','Reported condition','Town','Post-dispatch instructions','Postcode','Alerts','Incident notes'],patient:['Patient name','NHS number','Date of birth','Age','Address','Next of kin','Allergies','RESPECT / DNAR','GP details','Hoarding status'],secondary:['Neurological','Respiratory','Cardiology / ECG','Gastrointestinal','Genitourinary','Integumentary','Musculoskeletal','Mental health','Working diagnosis','Care plan'],outcome:['Outcome','Destination','ATMIST','SBAR','Pre-alert details','Persons accompanying patient'],sign:['Clinician name','Role','Professional PIN','Date','Time'],timings:['Call received','Mobile','At scene','Patient contact','Leave scene','At hospital','Handover complete']};
const key=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'_');
function buildGrid(id,items){items.forEach((label,i)=>{const d=document.createElement('div');d.className='field '+((i===items.length-1||/notes|ATMIST|SBAR/.test(label))?'span-2':'');d.innerHTML=`<label>${label}</label><textarea data-key="${key(label)}"></textarea>`;$(id).appendChild(d);});}
buildGrid('incidentGrid',schemas.incident);buildGrid('patientGrid',schemas.patient);buildGrid('secondaryGrid',schemas.secondary);buildGrid('outcomeGrid',schemas.outcome);buildGrid('timingsGrid',schemas.timings);
[['Category 1','category-1'],['Category 2','category-2'],['Category 3','category-3'],['Category 4','category-4']].forEach(([name,cls])=>{const b=document.createElement('button');b.className=`priority-option ${cls}`;b.textContent=name;b.onclick=()=>{document.querySelectorAll('.priority-option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');localStorage.setItem('prf_priority',name);saveDraft();};$('priorityGrid').appendChild(b);});
const primaryItems=[['D','Danger'],['R','Response'],['C','Catastrophic haemorrhage / C-spine'],['A','Airway'],['B','Breathing'],['C','Circulation'],['D','Disability'],['E','Exposure']];
primaryItems.forEach(([letter,label],i)=>{const row=document.createElement('div');row.className='primary-row';row.innerHTML=`<div class="primary-letter" data-primary-status="${i}">${letter}</div><div class="field"><label>${label}</label><textarea data-key="primary_${i}"></textarea></div>`;$('primaryRows').appendChild(row);});
function updatePrimary(){document.querySelectorAll('[data-primary-status]').forEach((box,i)=>box.classList.toggle('red',!!document.querySelector(`[data-key="primary_${i}"]`)?.value.trim()));}
['Capacity assessed','Consent obtained','Best-interests decision','DNACPR / ReSPECT checked','Safeguarding considered'].forEach((text,i)=>$('consentChecks').insertAdjacentHTML('beforeend',`<label><input type="checkbox" data-key="consent_${i}">${text}</label>`));
const traumaSteps=[['Step 1 - Vital signs',['RR under 10 or over 29','Systolic BP under 90','GCS motor 5 or less']],['Step 2 - Anatomy',['Chest injury with new oxygen requirement','Major pelvic fracture','Penetrating injury above knee or elbow','Suspected skull fracture','Spinal injury with paralysis','Multiple long-bone fractures','Amputation / mangled limb','Open fracture','Burns over 20%']],['Step 3 - Mechanism',['High-speed collision','Pedestrian or cyclist struck','Ejection','Death in same compartment','Significant fall','Crush, blast or penetrating mechanism']],['Step 4 - Special factors',['Older or frail patient','Pregnancy','Anticoagulant / antiplatelet use','Bleeding disorder','Significant clinical concern']],['Silver Trauma - Entry and indicators',['Age 65+ with low-energy fall','SBP under 110','HR over 100','RR over 30','GCS under 15','Injury to more than two areas','Unable to straight-leg raise','Pain prevents cough or deep breath','Severe uncontrolled pain','Bleeding disorder or anticoagulants']],['Silver Trauma - Actions',['Senior clinician / trauma desk contacted','Destination selected','Pre-alert completed','Analgesia documented','Medication history documented']]];
traumaSteps.forEach((step,i)=>{const d=document.createElement('div');d.className='trauma-step';d.innerHTML=`<h2>${step[0]}</h2>`;step[1].forEach((text,j)=>d.insertAdjacentHTML('beforeend',`<label><input type="checkbox" data-key="trauma_${i}_${j}">${text}</label>`));$('traumaTool').appendChild(d);});
function updateAlert(){const area=document.querySelector('[data-key="alerts"]');const has=!!area?.value.trim();$('alertBanner').textContent=has?'Alert':'No alerts';$('alertBanner').style.background=has?'#b11122':'#14833b';}
$('alertBanner').onclick=()=>{showPage('incident');setTimeout(()=>{const a=document.querySelector('[data-key="alerts"]');a.scrollIntoView({behavior:'smooth',block:'center'});a.focus();},60);};
function createTextCell(row,keyName,value='',type='text'){const td=row.insertCell();if(type==='time'){const i=document.createElement('input');i.type='time';i.dataset.col=keyName;i.value=value;td.appendChild(i);}else{const t=document.createElement('textarea');t.dataset.col=keyName;t.value=value;td.appendChild(t);grow(t);}return td;}
function deleteCell(row){const td=row.insertCell();const b=document.createElement('button');b.className='row-delete';b.textContent='×';b.onclick=()=>{row.remove();saveDraft();};td.appendChild(b);}
let activePickerButton=null;
function openPicker(title,options,button,multi=false){activePickerButton=button;$('pickerTitle').textContent=title;$('pickerChoices').innerHTML='';const current=new Set(button.dataset.values?JSON.parse(button.dataset.values):[]);options.forEach(value=>{const b=document.createElement('button');b.className='choice-button';b.textContent=value;b.classList.toggle('selected',current.has(value));b.onclick=()=>{if(multi){if(current.has(value))current.delete(value);else if(current.size<2)current.add(value);b.classList.toggle('selected',current.has(value));button.dataset.values=JSON.stringify([...current]);button.textContent=[...current].join(' / ')||'-';}else{button.textContent=value;button.dataset.values=JSON.stringify([value]);$('pickerModal').classList.remove('open');}saveDraft();};$('pickerChoices').appendChild(b);});$('pickerModal').classList.add('open');}
let activeGcs=null,activeNews=null;
window.addObs=function(v={}){const row=$('obsTable').tBodies[0].insertRow();['time','rr','spo2','bp','hr','temp','etco2','bm','ketones'].forEach(k=>createTextCell(row,k,v[k]||'',k==='time'?'time':'text'));let td=row.insertCell(),b=document.createElement('button');b.className='table-button avpu-button';b.textContent=v.avpu||'-';b.onclick=()=>openPicker('AVPU',['A - Alert','C - New confusion','V - Voice','P - Pain','U - Unresponsive'],b);td.appendChild(b);td=row.insertCell();b=document.createElement('button');b.className='table-button pupil-button';b.textContent=v.pupils||'-';b.dataset.values=JSON.stringify(v.pupilValues||[]);b.onclick=()=>openPicker('Select up to two pupil values',['0 mm','1 mm','2 mm','3 mm','4 mm','5 mm','6 mm','7 mm','8 mm','9 mm','10 mm'],b,true);td.appendChild(b);td=row.insertCell();b=document.createElement('button');b.className='table-button gcs-button';b.textContent=v.gcs||'-';b.onclick=()=>{activeGcs=b;$('gcsModal').classList.add('open');refreshGcs();};td.appendChild(b);td=row.insertCell();b=document.createElement('button');b.className='table-button news-button';b.textContent=v.news2??'-';b.onclick=()=>{activeNews=b;newsSelections={};document.querySelectorAll('#newsTable td.selected').forEach(x=>x.classList.remove('selected'));$('newsModal').classList.add('open');refreshNews();};td.appendChild(b);if(v.news2!==undefined&&v.news2!=='-')paintNews(b,Number(v.news2),v.newsRed);deleteCell(row);};
const gcsData=[['Eye Opening',[['4: Spontaneous',4],['3: To verbal',3],['2: To pain',2],['1: No response',1]]],['Verbal Response',[['5: Oriented',5],['4: Confused',4],['3: Inappropriate',3],['2: Incomprehensible',2],['1: No response',1]]],['Motor Response',[['6: Obeys commands',6],['5: Localises pain',5],['4: Withdraws',4],['3: Flexion',3],['2: Extension',2],['1: No response',1]]]],gcsSelections={0:4,1:5,2:6};
gcsData.forEach((group,i)=>{const row=document.createElement('div');row.className='gcs-row';row.innerHTML=`<h3>${group[0]}</h3><div></div>`;group[1].forEach(([label,score])=>{const b=document.createElement('button');b.className='calc-choice';b.textContent=label;b.dataset.group=i;b.dataset.score=score;b.onclick=()=>{gcsSelections[i]=score;refreshGcs();};row.lastChild.appendChild(b);});$('gcsRows').appendChild(row);});
function refreshGcs(){document.querySelectorAll('[data-score]').forEach(b=>b.classList.toggle('selected',gcsSelections[b.dataset.group]===Number(b.dataset.score)));$('gcsTotal').textContent=Object.values(gcsSelections).reduce((a,b)=>a+b,0);}
$('gcsDone').onclick=()=>{activeGcs.textContent=$('gcsTotal').textContent;$('gcsModal').classList.remove('open');saveDraft();};
const newsRows=[['Respiration',[['8',3],['-',null],['9-11',1],['12-20',0],['-',null],['21-24',2],['25',3]]],['SpO2 Scale 1',[['91',3],['92-93',2],['94-95',1],['96',0],['-',null],['-',null],['-',null]]],['SpO2 Scale 2',[['83',3],['84-85',2],['86-87',1],['88-92 air',0],['93-94 O',1],['95-96 O',2],['97 O',3]]],['Air / oxygen',[['-',null],['-',null],['-',null],['Air',0],['-',null],['Oxygen',2],['-',null]]],['Systolic BP',[['90',3],['91-100',2],['101-110',1],['111-219',0],['-',null],['-',null],['220',3]]],['Heart rate',[['40',3],['-',null],['41-50',1],['51-90',0],['91-110',1],['111-130',2],['131',3]]],['Temperature',[['35.0',3],['-',null],['35.1-36.0',1],['36.1-38.0',0],['38.1-39.0',1],['39.1',2],['-',null]]],['Consciousness',[['-',null],['-',null],['-',null],['Alert',0],['-',null],['-',null],['CVPU',3]]]],newsSelections={};
newsRows.forEach((group,i)=>{const row=$('newsTable').tBodies[0].insertRow();row.insertCell().textContent=group[0];group[1].forEach(([label,score])=>{const td=row.insertCell();td.textContent=label;if(score!==null){td.className=`news-score-${score}`;td.onclick=()=>{newsSelections[i]=score;[...row.cells].forEach(c=>c.classList.remove('selected'));td.classList.add('selected');refreshNews();};}});});
function refreshNews(){$('newsTotal').textContent=Object.values(newsSelections).reduce((a,b)=>a+b,0);}
function paintNews(button,total,redScore=false){button.classList.remove('news-low','news-low-medium','news-medium','news-high');button.classList.add(total>=7?'news-high':total>=5?'news-medium':redScore?'news-low-medium':'news-low');}
$('newsDone').onclick=()=>{const total=Number($('newsTotal').textContent),red=Object.values(newsSelections).includes(3);activeNews.textContent=total;activeNews.dataset.redScore=red;paintNews(activeNews,total,red);$('newsModal').classList.remove('open');saveDraft();};
const tableColumns={interventions:['time','type','location','outcome','clinician','reason'],drugs:['time','drug','dose','route','location','outcome','reaction','clinician'],als:['time','event','shock','drug','clinician']};
window.addTableRow=function(name,v={}){const table=$(name+'Table'),row=table.tBodies[0].insertRow();tableColumns[name].forEach(k=>createTextCell(row,k,v[k]||'',k==='time'?'time':'text'));deleteCell(row);};
$('addObs').onclick=()=>addObs();$('addIntervention').onclick=()=>addTableRow('interventions');$('addDrug').onclick=()=>addTableRow('drugs');$('addAls').onclick=()=>addTableRow('als');
function previewFiles(input,output){output.innerHTML='';[...input.files].forEach(file=>{const r=new FileReader();r.onload=()=>{if(file.type.startsWith('image/')){const img=document.createElement('img');img.src=r.result;img.alt=file.name;output.appendChild(img);}else{const d=document.createElement('div');d.className='file-preview';d.textContent=file.name;output.appendChild(d);}};r.readAsDataURL(file);});}
$('ecgUpload').onchange=()=>previewFiles($('ecgUpload'),$('ecgPreview'));$('injuryUpload').onchange=()=>previewFiles($('injuryUpload'),$('injuryPreview'));$('showPpci').onclick=()=>$('ppciModal').classList.add('open');
$('timings').onclick=()=>$('timingsModal').classList.add('open');$('timingsDone').onclick=()=>{$('timingsModal').classList.remove('open');saveDraft();};$('printPdf').onclick=()=>{growAll();setTimeout(()=>window.print(),50);};
let timerInterval=null,timerStart=null,audioContext=null,metronomeInterval=null,metronomeSounding=false;
function formatElapsed(ms){const s=Math.floor(ms/1000),h=String(Math.floor(s/3600)).padStart(2,'0'),m=String(Math.floor((s%3600)/60)).padStart(2,'0'),sec=String(s%60).padStart(2,'0');return `${h}:${m}:${sec}`;}
function metronomeClick(){
  if(!audioContext||audioContext.state!=='running')return;
  const oscillator=audioContext.createOscillator(),gain=audioContext.createGain(),now=audioContext.currentTime;
  oscillator.frequency.setValueAtTime(950,now);gain.gain.setValueAtTime(0.22,now);gain.gain.exponentialRampToValueAtTime(0.001,now+0.045);
  oscillator.connect(gain);gain.connect(audioContext.destination);oscillator.start(now);oscillator.stop(now+0.05);
}
async function startMetronome(){
  audioContext=audioContext||new (window.AudioContext||window.webkitAudioContext)();
  if(audioContext.state==='suspended')await audioContext.resume();
  clearInterval(metronomeInterval);metronomeSounding=true;
  const bpm=Number($('metronomeRate').value)||120,period=60000/bpm;
  metronomeClick();metronomeInterval=setInterval(metronomeClick,period);
  $('metronomeToggle').textContent='Pause sound';localStorage.setItem('prf_metronome_bpm',String(bpm));
}
function pauseMetronome(){clearInterval(metronomeInterval);metronomeInterval=null;metronomeSounding=false;$('metronomeToggle').textContent='Resume sound';}
function startTimer(start=Date.now(),withSound=true){timerStart=start;clearInterval(timerInterval);$('cprTimer').classList.remove('hidden');const tick=()=>$('timerValue').textContent=formatElapsed(Date.now()-timerStart);tick();timerInterval=setInterval(tick,1000);localStorage.setItem('prf_cpr_timer_start',String(start));if(withSound)startMetronome();}
$('metronomeRate').onchange=()=>{localStorage.setItem('prf_metronome_bpm',$('metronomeRate').value);if(metronomeSounding)startMetronome();};
$('metronomeToggle').onclick=()=>metronomeSounding?pauseMetronome():startMetronome();
$('startCpr').onclick=()=>{const now=new Date(),time=now.toTimeString().slice(0,5);$('cprStarted').value=time;addTableRow('als',{time,event:'CPR started'});showPage('als');startTimer(now.getTime(),true);saveDraft();};
$('closeTimer').onclick=()=>{$('cprTimer').classList.add('hidden');clearInterval(timerInterval);pauseMetronome();localStorage.removeItem('prf_cpr_timer_start');};
const clinicianCanvases=new Map();let clinicianCounter=0;
function setupClinicianCanvas(canvas){
  const ctx=canvas.getContext('2d');ctx.lineWidth=3;ctx.lineCap='round';let drawing=false;
  const point=e=>{const r=canvas.getBoundingClientRect();return[(e.clientX-r.left)*canvas.width/r.width,(e.clientY-r.top)*canvas.height/r.height];};
  canvas.addEventListener('pointerdown',e=>{drawing=true;canvas.setPointerCapture(e.pointerId);ctx.beginPath();ctx.moveTo(...point(e));e.preventDefault();});
  canvas.addEventListener('pointermove',e=>{if(!drawing)return;ctx.lineTo(...point(e));ctx.stroke();e.preventDefault();});
  canvas.addEventListener('pointerup',e=>{drawing=false;saveDraft();e.preventDefault();});
  canvas.addEventListener('pointercancel',()=>drawing=false);clinicianCanvases.set(canvas.dataset.clinicianId,canvas);
}
function addClinicianCard(data={}){
  const id=data.id||`clinician_${++clinicianCounter}`;const card=document.createElement('div');card.className='clinician-card';card.dataset.clinicianId=id;
  card.innerHTML=`<div class="clinician-card-header"><h2>Clinician sign-off</h2><button type="button" class="remove-clinician">Remove clinician</button></div><div class="form-grid"><div class="field"><label>Clinician name</label><textarea data-clinician-field="name"></textarea></div><div class="field"><label>Role</label><textarea data-clinician-field="role"></textarea></div><div class="field"><label>Professional PIN</label><textarea data-clinician-field="pin"></textarea></div><div class="field"><label>Date</label><input type="date" data-clinician-field="date"></div><div class="field"><label>Time</label><input type="time" data-clinician-field="time"></div></div><canvas class="signature-canvas" width="800" height="180" data-clinician-id="${id}"></canvas><div class="clinician-controls"><button type="button" class="clear-clinician-signature">Clear signature</button></div>`;
  $('clinicianSignoffs').appendChild(card);Object.entries(data).forEach(([k,v])=>{const el=card.querySelector(`[data-clinician-field="${k}"]`);if(el)el.value=v||'';});
  const canvas=card.querySelector('canvas');setupClinicianCanvas(canvas);if(data.signature){const img=new Image();img.onload=()=>canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);img.src=data.signature;}
  card.querySelector('.clear-clinician-signature').onclick=()=>{canvas.getContext('2d').clearRect(0,0,canvas.width,canvas.height);saveDraft();};
  card.querySelector('.remove-clinician').onclick=()=>{if(document.querySelectorAll('.clinician-card').length<=2){alert('At least two clinician sign-off forms must remain.');return;}clinicianCanvases.delete(id);card.remove();renumberClinicians();saveDraft();};
  growAll(card);renumberClinicians();return card;
}
function renumberClinicians(){document.querySelectorAll('.clinician-card').forEach((card,i)=>card.querySelector('h2').textContent=`Clinician ${i+1} sign-off`);}
function collectClinicians(){return [...document.querySelectorAll('.clinician-card')].map(card=>{const out={id:card.dataset.clinicianId};card.querySelectorAll('[data-clinician-field]').forEach(el=>out[el.dataset.clinicianField]=el.value);out.signature=card.querySelector('canvas').toDataURL();return out;});}
function restoreClinicians(items=[]){$('clinicianSignoffs').innerHTML='';clinicianCanvases.clear();clinicianCounter=0;(items.length?items:[{},{}]).forEach(addClinicianCard);while(document.querySelectorAll('.clinician-card').length<2)addClinicianCard();}
$('addClinician').onclick=()=>{addClinicianCard();saveDraft();};
$('showAlsGuidelines').onclick=()=>$('alsGuidelinesModal').classList.add('open');
$('caseId').textContent=localStorage.getItem('prf_case_id')||`PRF-${Date.now().toString().slice(-8)}`;localStorage.setItem('prf_case_id',$('caseId').textContent);
function serializeRows(name){return [...$(name+'Table').tBodies[0].rows].map(row=>{const out={};row.querySelectorAll('[data-col]').forEach(x=>out[x.dataset.col]=x.value);if(name==='obs'){const av=row.querySelector('.avpu-button'),pu=row.querySelector('.pupil-button'),gc=row.querySelector('.gcs-button'),ne=row.querySelector('.news-button');out.avpu=av.textContent;out.pupils=pu.textContent;out.pupilValues=JSON.parse(pu.dataset.values||'[]');out.gcs=gc.textContent;out.news2=ne.textContent;out.newsRed=ne.dataset.redScore==='true';}return out;});}
function collect(){const data={version:7,caseId:$('caseId').textContent,savedAt:new Date().toISOString(),priority:localStorage.getItem('prf_priority'),fields:{},obs:serializeRows('obs'),interventions:serializeRows('interventions'),drugs:serializeRows('drugs'),als:serializeRows('als'),clinicians:collectClinicians()};document.querySelectorAll('[data-key]').forEach(x=>data.fields[x.dataset.key]=x.type==='checkbox'?x.checked:x.value);return data;}
function saveDraft(){localStorage.setItem('prf_current',JSON.stringify(collect()));}
function populate(data){document.querySelectorAll('[data-key]').forEach(x=>{const v=data.fields?.[x.dataset.key];if(v!==undefined)x.type==='checkbox'?x.checked=!!v:x.value=v;});['obs','interventions','drugs','als'].forEach(n=>$(n+'Table').tBodies[0].innerHTML='');(data.obs||[]).forEach(addObs);(data.interventions||[]).forEach(v=>addTableRow('interventions',v));(data.drugs||[]).forEach(v=>addTableRow('drugs',v));(data.als||[]).forEach(v=>addTableRow('als',v));restoreClinicians(data.clinicians||[]);growAll();updatePrimary();updateAlert();}
$('saveCase').onclick=()=>{const data=collect(),name=prompt('Case name',data.fields.patient_name||data.caseId);if(!name)return;data.name=name;localStorage.setItem('prf_saved_'+Date.now(),JSON.stringify(data));alert('Case saved');};
$('openCase').onclick=()=>{const cases=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith('prf_saved_'))try{cases.push(JSON.parse(localStorage.getItem(k)));}catch{}}if(!cases.length){$('caseFile').click();return;}const n=Number(prompt(cases.map((c,i)=>`${i+1}. ${c.name||c.caseId}`).join('\n')));if(cases[n-1])populate(cases[n-1]);};
$('caseFile').onchange=e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{populate(JSON.parse(r.result));}catch{alert('Invalid case file');}};r.readAsText(file);};
$('exportJson').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(collect(),null,2)],{type:'application/json'}));a.download=$('caseId').textContent+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
restoreClinicians();try{const current=localStorage.getItem('prf_current');if(current)populate(JSON.parse(current));}catch{}
if(!$('obsTable').tBodies[0].rows.length)addObs();if(!$('interventionsTable').tBodies[0].rows.length)addTableRow('interventions');if(!$('drugsTable').tBodies[0].rows.length)addTableRow('drugs');if(!$('alsTable').tBodies[0].rows.length)addTableRow('als');
const savedPriority=localStorage.getItem('prf_priority');if(savedPriority)[...document.querySelectorAll('.priority-option')].find(b=>b.textContent===savedPriority)?.classList.add('selected');const savedBpm=localStorage.getItem('prf_metronome_bpm');if(savedBpm)$('metronomeRate').value=savedBpm;const savedTimer=Number(localStorage.getItem('prf_cpr_timer_start'));if(savedTimer)startTimer(savedTimer,false);showPage(localStorage.getItem('prf_page')||'incident');updatePrimary();updateAlert();growAll();
